# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: pablorcruh
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: auction-service
# "service" is the name of this project. This will also be added to your AWS resource names.
service: auction-service

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  environment:
    AUCTION_TABLE_NAME: ${self:custom.AuctionTable.name}
    MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
  iam:
    role:
      statements:
        - ${file(iam/AuctionTableIAM.yml):AuctionTableIAM}
        - ${file(./iam/MailQueueIAM.yml):MailQueueIAM}
  httpApi:
    authorizers:
      customLambdaAuthorizer:
        type: request
        functionArn: ${self:custom.Authorizer.name}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - httpApi:
          path: /auction
          method: post
          authorizer:
            name: customLambdaAuthorizer
  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - httpApi:
          path: /auctions
          method: get
          authorizer:
            name: customLambdaAuthorizer
  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - httpApi:
          path: /auctions/{id}
          method: get
          authorizer:
            name: customLambdaAuthorizer
  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - httpApi:
          path: /auctions/{id}/bid
          method: patch
          authorizer:
            name: customLambdaAuthorizer

  processAuctions:
    handler: src/handlers/processAuctions.processAuctions
    events:
      - eventBridge:
          schedule: rate(5 minutes)

custom:
  Authorizer:
    name: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:auth-service-${self:provider.stage}-custom-authorizer'
  AuctionTable:
    name: !Ref AuctionTable
    arn: !GetAtt AuctionTable.Arn
  MailQueue:
   arn: ${cf:notification-service-${self:provider.stage}.MailQueueArn}
   url: ${cf:notification-service-${self:provider.stage}.MailQueueUrl}


resources:
  Resources:
    AuctionTable: ${file(resources/AuctionTable.yml):AuctionTable}
      